export const OVMFactoryContract = {
  abi: [
    {
      inputs: [
        {
          internalType: 'address',
          name: '_consolidationSystemContract',
          type: 'address',
        },
        {
          internalType: 'address',
          name: '_withdrawalSystemContract',
          type: 'address',
        },
        {
          internalType: 'address',
          name: '_depositSystemContract',
          type: 'address',
        },
        { internalType: 'string', name: '_ensName', type: 'string' },
        {
          internalType: 'address',
          name: '_ensReverseRegistrar',
          type: 'address',
        },
        { internalType: 'address', name: '_ensOwner', type: 'address' },
      ],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    { inputs: [], name: 'Invalid_Owner', type: 'error' },
    { inputs: [], name: 'Invalid__Recipients', type: 'error' },
    { inputs: [], name: 'Invalid__ThresholdTooLarge', type: 'error' },
    { inputs: [], name: 'Invalid__ZeroThreshold', type: 'error' },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'ovm',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'owner',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'address',
          name: 'beneficiary',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'address',
          name: 'rewardRecipient',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint64',
          name: 'principalThreshold',
          type: 'uint64',
        },
      ],
      name: 'CreateObolValidatorManager',
      type: 'event',
    },
    {
      inputs: [],
      name: 'consolidationSystemContract',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'owner', type: 'address' },
        { internalType: 'address', name: 'beneficiary', type: 'address' },
        { internalType: 'address', name: 'rewardRecipient', type: 'address' },
        { internalType: 'uint64', name: 'principalThreshold', type: 'uint64' },
      ],
      name: 'createObolValidatorManager',
      outputs: [
        {
          internalType: 'contract ObolValidatorManager',
          name: 'ovm',
          type: 'address',
        },
      ],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'depositSystemContract',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'withdrawalSystemContract',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
  ],
};

export const OVMContract = {
  abi: [
    {
      inputs: [
        {
          internalType: 'address',
          name: '_consolidationSystemContract',
          type: 'address',
        },
        {
          internalType: 'address',
          name: '_withdrawalSystemContract',
          type: 'address',
        },
        {
          internalType: 'address',
          name: '_depositSystemContract',
          type: 'address',
        },
        { internalType: 'address', name: '_owner', type: 'address' },
        { internalType: 'address', name: '_beneficiary', type: 'address' },
        { internalType: 'address', name: '_rewardRecipient', type: 'address' },
        { internalType: 'uint64', name: '_principalThreshold', type: 'uint64' },
      ],
      stateMutability: 'nonpayable',
      type: 'constructor',
    },
    { inputs: [], name: 'InvalidConsolidation_Failed', type: 'error' },
    { inputs: [], name: 'InvalidDistribution_TooLarge', type: 'error' },
    { inputs: [], name: 'InvalidRequest_NotEnoughFee', type: 'error' },
    { inputs: [], name: 'InvalidRequest_Params', type: 'error' },
    { inputs: [], name: 'InvalidRequest_SystemGetFee', type: 'error' },
    { inputs: [], name: 'InvalidWithdrawal_Failed', type: 'error' },
    { inputs: [], name: 'NewOwnerIsZeroAddress', type: 'error' },
    { inputs: [], name: 'NoHandoverRequest', type: 'error' },
    { inputs: [], name: 'Unauthorized', type: 'error' },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'newBeneficiary',
          type: 'address',
        },
      ],
      name: 'BeneficiaryUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'bytes',
          name: 'srcPubKey',
          type: 'bytes',
        },
        {
          indexed: false,
          internalType: 'bytes',
          name: 'targetPubKey',
          type: 'bytes',
        },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'fee',
          type: 'uint256',
        },
      ],
      name: 'ConsolidationRequested',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'uint256',
          name: 'principalPayout',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'rewardPayout',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'pullOrPush',
          type: 'uint256',
        },
      ],
      name: 'DistributeFunds',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'pendingOwner',
          type: 'address',
        },
      ],
      name: 'OwnershipHandoverCanceled',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'pendingOwner',
          type: 'address',
        },
      ],
      name: 'OwnershipHandoverRequested',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'oldOwner',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'newOwner',
          type: 'address',
        },
      ],
      name: 'OwnershipTransferred',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'uint256',
          name: 'newPrincipalStakeAmount',
          type: 'uint256',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'oldPrincipalStakeAmount',
          type: 'uint256',
        },
      ],
      name: 'PrincipalStakeAmountUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'account',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'amount',
          type: 'uint256',
        },
      ],
      name: 'PullBalanceWithdrawn',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'nonOVMToken',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'recipient',
          type: 'address',
        },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'amount',
          type: 'uint256',
        },
      ],
      name: 'RecoverNonOVMFunds',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'newRewardRecipient',
          type: 'address',
        },
      ],
      name: 'RewardRecipientUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'user',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'roles',
          type: 'uint256',
        },
      ],
      name: 'RolesUpdated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'beneficiary',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'amount',
          type: 'uint256',
        },
      ],
      name: 'Swept',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'newBeneficiary',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'address',
          name: 'newOwner',
          type: 'address',
        },
      ],
      name: 'Transferred',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: 'address',
          name: 'excessFeeRecipient',
          type: 'address',
        },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'excessFee',
          type: 'uint256',
        },
      ],
      name: 'UnsentExcessFee',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'bytes',
          name: 'pubKey',
          type: 'bytes',
        },
        {
          indexed: true,
          internalType: 'uint64',
          name: 'amount',
          type: 'uint64',
        },
        {
          indexed: true,
          internalType: 'uint256',
          name: 'fee',
          type: 'uint256',
        },
      ],
      name: 'WithdrawalRequested',
      type: 'event',
    },
    {
      inputs: [],
      name: 'CONSOLIDATION_ROLE',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'DEPOSIT_ROLE',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'RECOVER_FUNDS_ROLE',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'SET_BENEFICIARY_ROLE',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'SET_REWARD_ROLE',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'WITHDRAWAL_ROLE',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'amountOfPrincipalStake',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'cancelOwnershipHandover',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'pendingOwner', type: 'address' },
      ],
      name: 'completeOwnershipHandover',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [
        {
          components: [
            { internalType: 'bytes[]', name: 'srcPubKeys', type: 'bytes[]' },
            { internalType: 'bytes', name: 'targetPubKey', type: 'bytes' },
          ],
          internalType: 'struct IObolValidatorManager.ConsolidationRequest[]',
          name: 'requests',
          type: 'tuple[]',
        },
        {
          internalType: 'uint256',
          name: 'maxFeePerConsolidation',
          type: 'uint256',
        },
        {
          internalType: 'address',
          name: 'excessFeeRecipient',
          type: 'address',
        },
      ],
      name: 'consolidate',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'consolidationSystemContract',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes', name: 'pubkey', type: 'bytes' },
        {
          internalType: 'bytes',
          name: 'withdrawal_credentials',
          type: 'bytes',
        },
        { internalType: 'bytes', name: 'signature', type: 'bytes' },
        { internalType: 'bytes32', name: 'deposit_data_root', type: 'bytes32' },
      ],
      name: 'deposit',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'depositSystemContract',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'distributeFunds',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'distributeFundsPull',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'fundsPendingWithdrawal',
      outputs: [{ internalType: 'uint128', name: '', type: 'uint128' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'getBeneficiary',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
      name: 'getPullBalance',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'user', type: 'address' },
        { internalType: 'uint256', name: 'roles', type: 'uint256' },
      ],
      name: 'grantRoles',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'user', type: 'address' },
        { internalType: 'uint256', name: 'roles', type: 'uint256' },
      ],
      name: 'hasAllRoles',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'user', type: 'address' },
        { internalType: 'uint256', name: 'roles', type: 'uint256' },
      ],
      name: 'hasAnyRole',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'owner',
      outputs: [{ internalType: 'address', name: 'result', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'pendingOwner', type: 'address' },
      ],
      name: 'ownershipHandoverExpiresAt',
      outputs: [{ internalType: 'uint256', name: 'result', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'principalRecipient',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'principalThreshold',
      outputs: [{ internalType: 'uint64', name: '', type: 'uint64' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'nonOVMToken', type: 'address' },
        { internalType: 'address', name: 'recipient', type: 'address' },
      ],
      name: 'recoverFunds',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'renounceOwnership',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'roles', type: 'uint256' }],
      name: 'renounceRoles',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'requestOwnershipHandover',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'user', type: 'address' },
        { internalType: 'uint256', name: 'roles', type: 'uint256' },
      ],
      name: 'revokeRoles',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'rewardRecipient',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'user', type: 'address' }],
      name: 'rolesOf',
      outputs: [{ internalType: 'uint256', name: 'roles', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'newAmount', type: 'uint256' }],
      name: 'setAmountOfPrincipalStake',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'newBeneficiary', type: 'address' },
      ],
      name: 'setBeneficiary',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        {
          internalType: 'address',
          name: 'newRewardRecipient',
          type: 'address',
        },
      ],
      name: 'setRewardRecipient',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'beneficiary', type: 'address' },
        { internalType: 'uint256', name: 'amount', type: 'uint256' },
      ],
      name: 'sweep',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        { internalType: 'uint256', name: '', type: 'uint256' },
      ],
      name: 'sweepToBeneficiaryContract',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'newBeneficiary', type: 'address' },
        { internalType: 'address', name: 'newOwner', type: 'address' },
      ],
      name: 'transfer',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
      name: 'transferOwnership',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'version',
      outputs: [{ internalType: 'string', name: '', type: 'string' }],
      stateMutability: 'pure',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'bytes[]', name: 'pubKeys', type: 'bytes[]' },
        { internalType: 'uint64[]', name: 'amounts', type: 'uint64[]' },
        {
          internalType: 'uint256',
          name: 'maxFeePerWithdrawal',
          type: 'uint256',
        },
        {
          internalType: 'address',
          name: 'excessFeeRecipient',
          type: 'address',
        },
      ],
      name: 'withdraw',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
      name: 'withdrawPullBalance',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'withdrawalSystemContract',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    { stateMutability: 'payable', type: 'receive' },
  ],
};
