export const OVMFactoryContract = {
  abi: [
    {
      inputs: [
        {
          internalType: "address",
          name: "_consolidationSystemContract",
          type: "address",
        },
        {
          internalType: "address",
          name: "_withdrawalSystemContract",
          type: "address",
        },
        {
          internalType: "address",
          name: "_depositSystemContract",
          type: "address",
        },
      ],
      stateMutability: "nonpayable",
      type: "constructor",
    },
    { inputs: [], name: "Invalid_Owner", type: "error" },
    { inputs: [], name: "Invalid__Recipients", type: "error" },
    { inputs: [], name: "Invalid__ThresholdTooLarge", type: "error" },
    { inputs: [], name: "Invalid__ZeroThreshold", type: "error" },
    {
      anonymous: false,
      inputs: [
        {
          indexed: true,
          internalType: "address",
          name: "ovm",
          type: "address",
        },
        {
          indexed: true,
          internalType: "address",
          name: "owner",
          type: "address",
        },
        {
          indexed: false,
          internalType: "address",
          name: "principalRecipient",
          type: "address",
        },
        {
          indexed: false,
          internalType: "address",
          name: "rewardRecipient",
          type: "address",
        },
        {
          indexed: false,
          internalType: "uint64",
          name: "principalThreshold",
          type: "uint64",
        },
      ],
      name: "CreateObolValidatorManager",
      type: "event",
    },
    {
      inputs: [],
      name: "consolidationSystemContract",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [
        { internalType: "address", name: "owner", type: "address" },
        {
          internalType: "address",
          name: "principalRecipient",
          type: "address",
        },
        { internalType: "address", name: "rewardRecipient", type: "address" },
        { internalType: "uint64", name: "principalThreshold", type: "uint64" },
      ],
      name: "createObolValidatorManager",
      outputs: [
        {
          internalType: "contract ObolValidatorManager",
          name: "ovm",
          type: "address",
        },
      ],
      stateMutability: "nonpayable",
      type: "function",
    },
    {
      inputs: [],
      name: "depositSystemContract",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
    {
      inputs: [],
      name: "withdrawalSystemContract",
      outputs: [{ internalType: "address", name: "", type: "address" }],
      stateMutability: "view",
      type: "function",
    },
  ],
};
export const OVMContract = {
  abi: [
    {
      type: "constructor",
      inputs: [
        {
          name: "_consolidationSystemContract",
          type: "address",
          internalType: "address",
        },
        {
          name: "_withdrawalSystemContract",
          type: "address",
          internalType: "address",
        },
        {
          name: "_depositSystemContract",
          type: "address",
          internalType: "address",
        },
        { name: "_owner", type: "address", internalType: "address" },
        {
          name: "_principalRecipient",
          type: "address",
          internalType: "address",
        },
        { name: "_rewardRecipient", type: "address", internalType: "address" },
        { name: "_principalThreshold", type: "uint64", internalType: "uint64" },
      ],
      stateMutability: "nonpayable",
    },
    { type: "receive", stateMutability: "payable" },
    {
      type: "function",
      name: "CONSOLIDATION_ROLE",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "RECOVER_FUNDS_ROLE",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "SET_PRINCIPAL_ROLE",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "WITHDRAWAL_ROLE",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "amountOfPrincipalStake",
      inputs: [],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "cancelOwnershipHandover",
      inputs: [],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "completeOwnershipHandover",
      inputs: [
        { name: "pendingOwner", type: "address", internalType: "address" },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "consolidationSystemContract",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "deposit",
      inputs: [
        { name: "pubkey", type: "bytes", internalType: "bytes" },
        {
          name: "withdrawal_credentials",
          type: "bytes",
          internalType: "bytes",
        },
        { name: "signature", type: "bytes", internalType: "bytes" },
        { name: "deposit_data_root", type: "bytes32", internalType: "bytes32" },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "depositSystemContract",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "distributeFunds",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "distributeFundsPull",
      inputs: [],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "fundsPendingWithdrawal",
      inputs: [],
      outputs: [{ name: "", type: "uint128", internalType: "uint128" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "getPullBalance",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
      outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "grantRoles",
      inputs: [
        { name: "user", type: "address", internalType: "address" },
        { name: "roles", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "hasAllRoles",
      inputs: [
        { name: "user", type: "address", internalType: "address" },
        { name: "roles", type: "uint256", internalType: "uint256" },
      ],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "hasAnyRole",
      inputs: [
        { name: "user", type: "address", internalType: "address" },
        { name: "roles", type: "uint256", internalType: "uint256" },
      ],
      outputs: [{ name: "", type: "bool", internalType: "bool" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "owner",
      inputs: [],
      outputs: [{ name: "result", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "ownershipHandoverExpiresAt",
      inputs: [
        { name: "pendingOwner", type: "address", internalType: "address" },
      ],
      outputs: [{ name: "result", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "principalRecipient",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "principalThreshold",
      inputs: [],
      outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "recoverFunds",
      inputs: [
        { name: "nonOVMToken", type: "address", internalType: "address" },
        { name: "recipient", type: "address", internalType: "address" },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "renounceOwnership",
      inputs: [],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "renounceRoles",
      inputs: [{ name: "roles", type: "uint256", internalType: "uint256" }],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "requestConsolidation",
      inputs: [
        { name: "sourcePubKeys", type: "bytes[]", internalType: "bytes[]" },
        { name: "targetPubKey", type: "bytes", internalType: "bytes" },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "requestOwnershipHandover",
      inputs: [],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "requestWithdrawal",
      inputs: [
        { name: "pubKeys", type: "bytes[]", internalType: "bytes[]" },
        { name: "amounts", type: "uint64[]", internalType: "uint64[]" },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "revokeRoles",
      inputs: [
        { name: "user", type: "address", internalType: "address" },
        { name: "roles", type: "uint256", internalType: "uint256" },
      ],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "rewardRecipient",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "rolesOf",
      inputs: [{ name: "user", type: "address", internalType: "address" }],
      outputs: [{ name: "roles", type: "uint256", internalType: "uint256" }],
      stateMutability: "view",
    },
    {
      type: "function",
      name: "setPrincipalRecipient",
      inputs: [
        {
          name: "newPrincipalRecipient",
          type: "address",
          internalType: "address",
        },
      ],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "transferOwnership",
      inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "payable",
    },
    {
      type: "function",
      name: "withdraw",
      inputs: [{ name: "account", type: "address", internalType: "address" }],
      outputs: [],
      stateMutability: "nonpayable",
    },
    {
      type: "function",
      name: "withdrawalSystemContract",
      inputs: [],
      outputs: [{ name: "", type: "address", internalType: "address" }],
      stateMutability: "view",
    },
    {
      type: "event",
      name: "ConsolidationRequested",
      inputs: [
        {
          name: "requester",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        { name: "source", type: "bytes", indexed: true, internalType: "bytes" },
        { name: "target", type: "bytes", indexed: true, internalType: "bytes" },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "DistributeFunds",
      inputs: [
        {
          name: "principalPayout",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "rewardPayout",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
        {
          name: "pullOrPush",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "NewPrincipalRecipient",
      inputs: [
        {
          name: "newPrincipalRecipient",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "oldPrincipalRecipient",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipHandoverCanceled",
      inputs: [
        {
          name: "pendingOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipHandoverRequested",
      inputs: [
        {
          name: "pendingOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "OwnershipTransferred",
      inputs: [
        {
          name: "oldOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "newOwner",
          type: "address",
          indexed: true,
          internalType: "address",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RecoverNonOVMFunds",
      inputs: [
        {
          name: "nonOVMToken",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "recipient",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "RolesUpdated",
      inputs: [
        {
          name: "user",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "roles",
          type: "uint256",
          indexed: true,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "Withdrawal",
      inputs: [
        {
          name: "account",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    {
      type: "event",
      name: "WithdrawalRequested",
      inputs: [
        {
          name: "requester",
          type: "address",
          indexed: true,
          internalType: "address",
        },
        { name: "pubKey", type: "bytes", indexed: true, internalType: "bytes" },
        {
          name: "amount",
          type: "uint256",
          indexed: false,
          internalType: "uint256",
        },
      ],
      anonymous: false,
    },
    { type: "error", name: "InvalidConsolidation_Failed", inputs: [] },
    { type: "error", name: "InvalidDistribution_TooLarge", inputs: [] },
    { type: "error", name: "InvalidRequest_NotEnoughFee", inputs: [] },
    { type: "error", name: "InvalidRequest_Params", inputs: [] },
    { type: "error", name: "InvalidRequest_SystemGetFee", inputs: [] },
    { type: "error", name: "InvalidWithdrawal_Failed", inputs: [] },
    { type: "error", name: "NewOwnerIsZeroAddress", inputs: [] },
    { type: "error", name: "NoHandoverRequest", inputs: [] },
    { type: "error", name: "Unauthorized", inputs: [] },
  ] as const,
};
