name: Publish Obol-SDK to NPM

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # Required to make GitHub forget this checkout for the next step

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@obolnetwork'

      - run: yarn install --frozen-lockfile

      - run: yarn run build

      - run: yarn run generate-typedoc 

      - run: yarn run ds:release:patch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
