name: Release PR
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Choose release type
        options:
          - auto
          - patch
          - minor
          - major
        default: auto
jobs:
  releaseIt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: npm

      - name: Install dependancies
        run: yarn install --frozen-lockfile

      - name: Prepare release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPE_ARG: ${{ fromJSON('{"auto":"", "patch":"patch", "minor":"minor", "major":"major"}')[github.event.inputs.type] }}
        run: yarn run release $TYPE_ARG --ci --verbose --no-git.push --no-git.commit --no-git.tag --no-github
      
      - name: Update e2e dependencies
        working-directory: ./test/sdk-package
        run: yarn upgrade

      - name: Show git status
        if: failure()
        run: git status && git diff

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        id: cpr
        with:
          branch: release
          delete-branch: true
          commit-message: 'chore(release): v${{ steps.package-version.outputs.current-version}}'
          title: '[Release] v${{ steps.package-version.outputs.current-version}}'
          body: |
            Release notes for this release found in [CHANGELOG.md](https://github.com/ObolNetwork/obol-sdk/blob/release/CHANGELOG.md)
          labels: |
            release
            automated pr
          signoff: false
          draft: false
